# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui_files/report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report(object):
    def setupUi(self, Report):
        Report.setObjectName("Report")
        Report.resize(976, 830)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Report.sizePolicy().hasHeightForWidth())
        Report.setSizePolicy(sizePolicy)
        Report.setMinimumSize(QtCore.QSize(0, 0))
        Report.setMaximumSize(QtCore.QSize(2000000, 2000000))
        self.scrollArea = QtWidgets.QScrollArea(Report)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 971, 751))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 969, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(2, 0, 971, 751))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(Report)
        self.pushButton.setGeometry(QtCore.QRect(590, 780, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Report)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 780, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Report)
        QtCore.QMetaObject.connectSlotsByName(Report)

    def retranslateUi(self, Report):
        _translate = QtCore.QCoreApplication.translate
        Report.setWindowTitle(_translate("Report", "Отчет"))
        self.pushButton.setText(_translate("Report", "Сохранить"))
        self.pushButton_2.setText(_translate("Report", "Закрыть"))
