# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\ui_files\report.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report(object):
    def setupUi(self, Report):
        Report.setObjectName("Report")
        Report.resize(820, 830)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Report.sizePolicy().hasHeightForWidth())
        Report.setSizePolicy(sizePolicy)
        Report.setMinimumSize(QtCore.QSize(0, 0))
        Report.setMaximumSize(QtCore.QSize(2000000, 2000000))
        Report.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\src\\ui_files\\../images/MathStab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Report.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Report)
        self.pushButton.setGeometry(QtCore.QRect(440, 790, 171, 31))
        font = QtGui.QFont()
        font.setFamily("CMU Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Report)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 790, 171, 31))
        font = QtGui.QFont()
        font.setFamily("CMU Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(Report)
        self.frame.setGeometry(QtCore.QRect(0, 0, 821, 771))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(Report)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 790, 411, 31))
        font = QtGui.QFont()
        font.setFamily("CMU Serif")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setObjectName("label")

        self.retranslateUi(Report)
        QtCore.QMetaObject.connectSlotsByName(Report)

    def retranslateUi(self, Report):
        _translate = QtCore.QCoreApplication.translate
        Report.setWindowTitle(_translate("Report", "Отчет"))
        self.pushButton.setText(_translate("Report", "Сохранить"))
        self.pushButton_2.setText(_translate("Report", "Закрыть"))
        self.label.setText(_translate("Report", "<html><head/><body><p><span style=\" color:#00aa00;\">Файл успешно сохранен</span></p></body></html>"))
